# Generated by Django 6.1 on 2026-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=220)),
                ('role', models.CharField(max_length=255)),
                ('availabilityStatus', models.BooleanField(default=True)),
                ('currentAssignment', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('accessLevel', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
