# Generated by Django 6.1 on 2026-08-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='userID',
        ),
    ]
