# Generated by Django 6.1 on 2026-09-28 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_timeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_number',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.timeblock'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
