# -----------------------------------------------------------------------------
# MIGRATION  (appointments/migrations/0002_remove_appointment_room_appointment_date_and_more.py)
#
# What is a migration? Django records every change to the models as a small
# Python file like this one. `python manage.py migrate` runs the files that have
# not been applied yet, in dependency order, and turns them into SQL for the
# database (db.sqlite3). That is how the database tables stay in step with
# models.py.
#
# This one: reshapes Appointment. The Room table/link is dropped and replaced by:
#   * date        - the appointment day,
#   * room_number - a simple text room number (default '000' = none yet),
#   * time_block  - which of the doctor's weekly blocks it uses (optional).
# Depends on doctors 0002 because TimeBlock is created there.
# -----------------------------------------------------------------------------
# Generated by Django 6.1 on 2026-09-28 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_timeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='room',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_number',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.timeblock'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
