# Generated by Django 6.1 on 2026-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_room_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SCHEDULED_WAITING', 'Scheduled Waiting'), ('DONE', 'Done')], default='PENDING_CONFIRMATION', max_length=30),
        ),
    ]
