# -----------------------------------------------------------------------------
# MIGRATION  (appointments/migrations/0003_appointment_status.py)
#
# What is a migration? Django records every change to the models as a small
# Python file like this one. `python manage.py migrate` runs the files that have
# not been applied yet, in dependency order, and turns them into SQL for the
# database (db.sqlite3). That is how the database tables stay in step with
# models.py.
#
# This one: adds Appointment.status (PENDING_CONFIRMATION / CONFIRMED /
# SCHEDULED_WAITING / DONE), defaulting to PENDING_CONFIRMATION.
# -----------------------------------------------------------------------------
# Generated by Django 6.1 on 2026-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_room_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SCHEDULED_WAITING', 'Scheduled Waiting'), ('DONE', 'Done')], default='PENDING_CONFIRMATION', max_length=30),
        ),
    ]
