"""
Django settings for UHAMS project.

UHAMS = "Hospital management" system. This file is the single place where the
whole project is configured: which apps are installed, which middleware runs on
every request, where templates and static files live, which database to use,
and how users are modelled.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# __file__ is .../UHAMS/UHAMS/settings.py, so .parent is the inner UHAMS
# package and .parent.parent is the outer project folder (the one that holds
# manage.py, templates/ and static/). Everything below is relative to it.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Django uses this key to sign session cookies, CSRF tokens and password-reset
# links. The "django-insecure-" prefix is Django's own marker that this is a
# throwaway development key. Before deploying, load a real key from an
# environment variable instead of committing it to source control.
SECRET_KEY = 'django-insecure-s$hrx2u=r9(g27a8#xh5uw6l_gk$^t@ff6b=n%_b@058e(*5oa'

# SECURITY WARNING: don't run with debug turned on in production!
# With DEBUG = True Django shows detailed error pages (leaking code and
# settings) and serves static files itself. Always set this to False on a
# real server.
DEBUG = True

# Hostnames the site may be served from. An empty list is fine while DEBUG is
# True (Django then allows localhost / 127.0.0.1); in production this must list
# your real domain(s), otherwise every request is rejected.
ALLOWED_HOSTS = []


# Application definition

# Every Django "app" that is part of this project. Django only discovers
# models, migrations, admin registrations, management commands and
# app-level template folders for apps listed here.
INSTALLED_APPS = [
    # --- Built-in Django apps ---
    'django.contrib.admin',          # the /admin/ back-office site
    'django.contrib.auth',           # user/password/permission machinery (we extend it)
    'django.contrib.contenttypes',   # lets models refer to other models generically
    'django.contrib.sessions',       # server-side sessions (used for our login, see core/views.py)
    'django.contrib.messages',       # one-off flash messages ("Saved!") shown after redirects
    'django.contrib.staticfiles',    # finds and serves CSS/JS/images

    # --- Our own apps (each is a folder in the project root) ---
    'core',          # custom User model, login/logout, settings page, shared helpers
    'staffs',        # hospital staff, vacations, staff assignments, emergency calls
    'patients',      # patient profiles, registration, booking appointments
    'doctors',       # doctor profiles, weekly time blocks, confirming appointments
    'drivers',       # ambulance driver profiles
    'appointments',  # the Appointment model that links a doctor to a patient
    'ambulances',    # the ambulance fleet and its status
]

# Middleware is a stack of small components that wrap every request/response.
# Order matters: requests go down the list, responses come back up it.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',          # HTTPS/security headers
    'django.contrib.sessions.middleware.SessionMiddleware',   # loads request.session from the cookie
    'django.middleware.common.CommonMiddleware',              # URL normalisation (trailing slashes etc.)
    'django.middleware.csrf.CsrfViewMiddleware',              # blocks forged POST requests ({% csrf_token %})
    'django.contrib.auth.middleware.AuthenticationMiddleware',# sets request.user (not used for our own login)
    'django.contrib.messages.middleware.MessageMiddleware',   # stores flash messages in the session
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # stops the site being embedded in iframes
]

# The "front door" URL file: Django starts matching every URL from here.
ROOT_URLCONF = 'UHAMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-wide template folder: templates/base.html, templates/login.html, ...
        # The per-feature subfolders (staffs-templates/, doctors-templates/, ...) live inside it
        # and are referenced by views as e.g. 'staffs-templates/call-list.html'.
        'DIRS': [BASE_DIR / 'templates'],
        # Also look for a "templates" folder inside each installed app
        # (this is how the admin site finds its own templates).
        'APP_DIRS': True,
        'OPTIONS': {
            # Context processors add variables to EVERY template automatically.
            'context_processors': [
                'django.template.context_processors.request',            # gives templates `request`
                'django.contrib.auth.context_processors.auth',           # gives templates `user` / `perms`
                'django.contrib.messages.context_processors.messages',   # gives templates `messages`

                # custom context processor
                # Adds `logged_in_user` and `is_staff_manager` to every page so
                # base.html can draw the right sidebar. See core/context_processors.py.
                'core.context_processors.load_logged_in_user',
            ],
        },
    },
]

# Dotted path to the WSGI callable that production servers import (UHAMS/wsgi.py).
WSGI_APPLICATION = 'UHAMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite stores the whole database in a single file (db.sqlite3) next to
# manage.py. It needs no server and is perfect for development; for a real
# hospital deployment you would switch to PostgreSQL or MySQL here.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# Replace Django's default User with our own (core.models.User), which adds a
# `role` (STAFF/DOCTOR/PATIENT/DRIVER) and a `phone` number. This must be set
# BEFORE the first migration is run, because every foreign key to "the user"
# (e.g. DoctorProfile.user) is built from this setting.
AUTH_USER_MODEL = "core.User"

# Rules a new password must pass. These run in validate_password(), which our
# registration/"change password" forms call (see staffs/forms.py, core/forms.py).
AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords that are too similar to the username, name or email.
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Requires at least 8 characters by default.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Rejects passwords found in a list of commonly used passwords.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Rejects passwords that are made only of digits.
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Times are stored and displayed in UTC. (Change this, e.g. to 'Asia/Dhaka',
# if dates/times such as "today" or appointment dates should follow local time.)
TIME_ZONE = 'UTC'

USE_I18N = True

# Store datetimes as timezone-aware values. timezone.now() / localdate() in
# the code rely on this being True.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# URL prefix under which static files are served: /static/css/style.css
STATIC_URL = 'static/'
# Extra folders (besides each app's own "static" folder) where Django looks for
# static files. Ours is <project>/static/ with css/, js/ and images/.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# NOTE: Django does not read a setting called MAILERS - the setting that
# controls email sending is EMAIL_BACKEND. As written, this block has no effect
# and Django falls back to its default (real SMTP). The project currently
# sends no email, so nothing breaks; if you add email later, the equivalent
# development setting is:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# which prints emails to the terminal instead of sending them.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
