# -----------------------------------------------------------------------------
# MIGRATION  (staffs/migrations/0001_initial.py)
#
# What is a migration? Django records every change to the models as a small
# Python file like this one. `python manage.py migrate` runs the files that have
# not been applied yet, in dependency order, and turns them into SQL for the
# database (db.sqlite3). That is how the database tables stay in step with
# models.py.
#
# This one: creates the first, minimal StaffProfile table (title, availability,
# current assignment, department, a free-text access_level) linked one-to-one to the User.
# Later migrations add many more columns.
# -----------------------------------------------------------------------------
# Generated by Django 6.1 on 2026-08-30 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('availability_status', models.BooleanField(default=True)),
                ('current_assignment', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('access_level', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
